#!/bin/sh

set -e -o pipefail

set --
set -- "$@" -j "${X11APPJAIL_JAIL}"
set -- "$@" -f "${X11APPJAIL_WORKDIR}/Makejail"

set -- "$@" -o alias -o ip4_disable -o ip6_disable

if [ -n "${X11APPJAIL_EPHEMERAL}" ] || \
        x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.jail.ephemeral" "${X11APPJAIL_UID}"; then
    set -- "$@" -o ephemeral
fi

if x11appjail sys-attr check mount.system-fonts; then
    PREFIX=`x11appjail prefix`
    FONTSDIR="${PREFIX}/share/fonts"

    if [ -d "${FONTSDIR}" ]; then
        set -- "$@" -o fstab="\"${FONTSDIR}\" /system-fonts nullfs ro"
    fi
fi

mkdir -p -m 0755 -- "${X11APPJAIL_USERDIR}"
set -- "$@" -o fstab="${X11APPJAIL_USERDIR} data <volumefs>"

set -- "$@" --
set -- "$@" --puid "${X11APPJAIL_UID}"
set -- "$@" --pgid "${X11APPJAIL_GID}"

OCI_FROM=
if x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.from"; then
    OCI_FROM=`x11appjail sys-attr cat "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.from"`
elif x11appjail sys-attr check "oci.from"; then
    OCI_FROM=`x11appjail sys-attr cat oci.from`
fi
if [ -n "${OCI_FROM}" ]; then
    set -- "$@" --from "${OCI_FROM}"
fi

OCI_TAG=
if x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.tag"; then
    OCI_TAG=`x11appjail sys-attr cat "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.tag"`
elif x11appjail sys-attr check "oci.tag"; then
    OCI_TAG=`x11appjail sys-attr cat oci.tag`
fi
if [ -n "${OCI_TAG}" ]; then
    set -- "$@" --tag "${OCI_TAG}"
fi

exec "${APPJAIL}" makejail "$@"
